{"name": "Проверка ошибки при создании двух одинаковых курьеров", "status": "passed", "start": 1717357822510, "stop": 1717357822715, "uuid": "fc7bc382-375a-41dc-ae88-cb22c3185202", "historyId": "2999d516797e75aa22ea8fd3575f9bd4", "testCaseId": "2999d516797e75aa22ea8fd3575f9bd4", "fullName": "tests.test_create_courier.TestCreateCourier#test_failed_create_duplicate_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "msknbfb5654inb"}, {"name": "thread", "value": "17632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}